sudo: false
language: node_js
node_js:
  - "8"
cache:
  yarn: true
  directories:
    - node_modules
before_install:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - yarn run lint
  - yarn test
notifications:
  email:
    on_success: never
    on_failure: never
before_deploy: yarn build
deploy:
  skip_cleanup: true
  provider: npm
  email: info@darwineducation.com
  tag: next
  api_key:
    secure: sOTrDUIxh8U0gtCk5gVKEyPjxqahC5NVCOUbCRekD7euzX/o/fgiUajRXQaqFDyPK5kn40iu0gJF4j5yGtHLym+5G2FkxyhGltXmJFmxZHJlt5BwEvPWCLu85ieIV5qO5baNLNC+8GIh3Wtu9XLNQ6lB97DmAZxcBC44HAvOIno3vTeurVvg09bZM6IYISfAGUKUUNkb0ZMMXdlsfrdh8tRolnUkOkvE0McymBZzZqET6xJciPQWAsgqnUizrT3DXKT2ygZ65aZrcX3Oa/MH8NfZTiyjKmU3jRl81oHTwrj5v55wu8aZDrQDguiRiLoAtjjJFUxx5GU2K5XQn+JPYzM0A7pcnrwfHM12oGNwJvVDAYdP7WLwJlc4dEpMqhjGsJrtsxkgVEokmDGr0BBDdzahCQSgdwiymR/ognMuYmve9E6YxwWPnwSVsUet/lrKxWgLvq1IqJnXBfWwWTe05gcCQBe4D1KM/qGQqsC5rySzLXX4DihlliXfC1bodb3PzAHa8VrTup+Zz2GslKm6Ihz0IczTQIqDJAwDE2YaVCyaG945ArKm0nd+pS4uYrkSwk9SwmyIpgpIp5rGEn0zz1jbtFROgPT4iLHwIBnlL6LImUKd6IewyRzAILHhaIN3NX9XnNWKcxoevU781ze7vLRPWCKclYaM2V0e20gBLNE=
  on:
    tags: true
    repo: darwin-education/resium
