[build]
  publish = "/.docz/dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

[[redirects]]
  from = "http://resium.netlify.com/*"
  to = "http://resium.darwineducation.com/:splat"
  status = 301
  force = true
